[package]
name = "g-flite"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = { version="1.0.91" }
serde_json = "1.0.39"
indicatif = "0.11.0"
console = ">=0.7.1, <1.0.0"
actix = "0.8.1"
log = "0.4.6"
env_logger = "0.6.1"
failure="0.1.5"
directories = "1.0.2"
golem-rpc-api = { git="https://github.com/golemfactory/golem-client" }
actix-wamp = { git="https://github.com/golemfactory/golem-client" }
wamp-derive = { git="https://github.com/golemfactory/golem-client" }
hound = { git="https://github.com/kubkon/hound" }

[[bin]]
name = "g_flite"
path = "src/main.rs"
